In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("CarPrice_Assignment.csv")
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

## Data Cleaning

In [ ]:
### Checking for null data
df.isnull().sum()
#No Null data, so there is no need for value imputation

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [ ]:
#Dropping car_id since its unnecessary

df=df.drop("car_ID",axis= 1 )

In [ ]:
#to check simple statistic
print("the length of the data is : ",len(df))
df.describe()

the length of the data is :  205

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [ ]:
#combining carlength + carwidth + carheight as car_volume
df["car_volume"] = df["carlength"] * df["carwidth"] * df["carheight"]

df = df.drop(columns=["carlength","carwidth","carheight"])

In [ ]:
#Removing Outliers
numerical_columns = df.select_dtypes(exclude=['object']).columns

def remove_outliers(df, cols):
    Q1 = df[cols].quantile(0.25)
    Q3 = df[cols].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    return df[~((df[cols] < lower_bound) | (df[cols] > upper_bound)).any(axis=1)]

df = remove_outliers(df, numerical_columns)
df_copy = df

### Categorical Variable

In [ ]:
## Working with categorical columns
## CarName ##
df.select_dtypes(include=["object"])
print(df["CarName"].value_counts())
print("\n ")
print (" We have 102 variation for 139 dataset. It seems that CarName format is Car_Brand *space* Car_type  We will be using Car Brand instead of car type to gave more generalized view")
df["CarBrand"] = df["CarName"].str.split(" ").str[0]

##droping the CarName Columns
df = df.drop(columns = ["CarName"],axis =1 )

toyota corona          5
toyota corolla         5
mazda 626              3
toyota mark ii         3
honda accord           2
                      ..
maxda rx3              1
isuzu D-Max V-Cross    1
isuzu MU-X             1
honda civic (auto)     1
volvo diesel           1
Name: CarName, Length: 104, dtype: int64


 We have 102 variation for 139 dataset. It seems that CarName format is Car_Brand *space* Car_type  We will be using Car Brand instead of car type to gave more generalized view

In [ ]:
## fueltype
print (df["fueltype"].value_counts())
print(" \n")
print("It seems that the option always gas, and hence there is no other variation and other distinguishable categories, hence we will drop the columns")

df = df.drop(columns = ["fueltype"],axis = 1 )

gas    142
Name: fueltype, dtype: int64


It seems that the option always gas, and hence there is no other variation and other distinguishable categories, hence we will drop the columns

In [ ]:
##aspiration
print (df["aspiration"].value_counts())

## we will use get_dummies for this

std      128
turbo     14
Name: aspiration, dtype: int64

In [ ]:
## door_number

door_number_replacement = {"two" : 2 ,
                           "four" : 4}

df = df.replace({"door_number":door_number_replacement})

print("we are replacing door because it can be represented as number /")

we are replacing door because it can be represented as number /

In [ ]:
df["carbody"].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [ ]:
df["drivewheel"].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [ ]:
print(df["enginelocation"].unique())
df = df.drop(columns = ["enginelocation"], axis = 1 )
print(" \n")
print("We will drop this because no other variation and other distinguishable categories, hence we will drop the columns")

['front']


We will drop this because no other variation and other distinguishable categories, hence we will drop the columns

In [ ]:
print(df["enginetype"].unique())

['dohc' 'ohcv' 'ohc' 'rotor' 'l']

In [ ]:
print(df["cylindernumber"].unique())

cylindernumber_replacement = {"four" : 4,
                            "six" : 6,
                            "five": 5,
                            "two" : 2 }

df = df.replace({"cylindernumber" : cylindernumber_replacement})

print("\n")
print("We replace cylindernumber from string to integer")

['four' 'six' 'five' 'two']


We replace cylindernumber from string to integer

In [ ]:
print(df["fuelsystem"].unique())

['mpfi' '2bbl' '1bbl' 'spfi' '4bbl' 'spdi']

In [ ]:
#Final dataset
df.head()

,symboling,aspiration,doornumber,carbody,drivewheel,wheelbase,curbweight,enginetype,cylindernumber,enginesize,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,car_volume,CarBrand
0,3,std,two,convertible,rwd,88.6,2548,dohc,4,130,...,3.47,2.68,9.0,111,5000,21,27,13495.0,528019.904,alfa-romero
1,3,std,two,convertible,rwd,88.6,2548,dohc,4,130,...,3.47,2.68,9.0,111,5000,21,27,16500.0,528019.904,alfa-romero
2,1,std,two,hatchback,rwd,94.5,2823,ohcv,6,152,...,2.68,3.47,9.0,154,5000,19,26,16500.0,587592.640,alfa-romero
3,2,std,four,sedan,fwd,99.8,2337,ohc,4,109,...,3.19,3.40,10.0,102,5500,24,30,13950.0,634816.956,audi
4,2,std,four,sedan,4wd,99.4,2824,ohc,5,136,...,3.19,3.40,8.0,115,5500,18,22,17450.0,636734.832,audi

## VIF Checking

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
numeric = df.select_dtypes(exclude=["object"])
numeric = numeric.drop("price",axis =1 )
dropped_vars = []

for i in range (14):
    vif = pd.DataFrame()
    vif["Variable"] = numeric.columns
    vif["VIF"] = [variance_inflation_factor(numeric.values, i) for i in range(numeric.shape[1])]
    if (vif["VIF"].max()) >=10 :
        new_columns = vif.sort_values(by = "VIF",ascending = False)[1:]['Variable'].unique().tolist()
        print(vif.sort_values(by = "VIF",ascending = False))
        print("\n \n \n \n \n ")
        dropped_vars.append(vif.sort_values(by = "VIF",ascending = False).iloc[0,0])
        numeric = numeric[new_columns]


final_columns = vif["Variable"].unique().tolist()
print(vif)

            Variable          VIF
1          wheelbase  2538.552755
5          boreratio  1451.428865
11        highwaympg   975.885042
10           citympg   716.015608
4         enginesize   540.197824
7   compressionratio   469.835539
12        car_volume   453.892316
2         curbweight   425.036125
6             stroke   415.502016
3     cylindernumber   393.146819
9            peakrpm   302.362244
8         horsepower    76.135014
0          symboling     2.781941






            Variable         VIF
1         highwaympg  965.142750
0          boreratio  870.130342
2            citympg  710.406742
4   compressionratio  466.192887
6         curbweight  409.555126
3         enginesize  392.833195
5         car_volume  341.765923
9            peakrpm  302.341806
8     cylindernumber  274.643939
7             stroke  269.995388
10        horsepower   75.976001
11         symboling    2.550245






            Variable         VIF
0          boreratio  743.966750
2   compressionratio  466.192186
3         curbweight  398.732579
4         enginesize  376.923538
5         car_volume  339.750129
6            peakrpm  297.673271
8             stroke  260.034043
7     cylindernumber  258.932167
1            citympg  158.817675
9         horsepower   75.973500
10         symboling    2.492105






           Variable         VIF
0  compressionratio  453.536349
1        curbweight  381.798290
3        car_volume  278.612093
4           peakrpm  269.712611
5            stroke  259.706270
2        enginesize  231.985701
7           citympg  119.583393
6    cylindernumber  114.765086
8        horsepower   75.105492
9         symboling    2.401673






         Variable         VIF
0      curbweight  358.242617
1      car_volume  273.093319
3          stroke  255.838139
4      enginesize  213.348804
2         peakrpm  210.642951
6  cylindernumber  110.165438
7      horsepower   73.099833
5         citympg   63.555711
8       symboling    1.972206






         Variable         VIF
1          stroke  254.575581
3         peakrpm  200.573341
2      enginesize  179.385875
0      car_volume  127.688520
4  cylindernumber  108.498410
5      horsepower   68.407194
6         citympg   59.886622
7       symboling    1.971320






         Variable         VIF
1      enginesize  162.715972
0         peakrpm  145.147733
2      car_volume  117.505866
3  cylindernumber  106.495732
4      horsepower   68.167346
5         citympg   49.814737
6       symboling    1.941393






         Variable         VIF
0         peakrpm  121.681016
1      car_volume   90.500944
2  cylindernumber   52.467468
4         citympg   49.751633
3      horsepower   45.537303
5       symboling    1.929791






         Variable        VIF
0      car_volume  68.514709
1  cylindernumber  50.258861
3      horsepower  37.988392
2         citympg  25.274077
4       symboling   1.636255






         Variable        VIF
0  cylindernumber  48.592793
1      horsepower  20.998766
2         citympg  14.957400
3       symboling   1.521464






     Variable       VIF
0  horsepower  4.774774
1     citympg  4.752377
2   symboling  1.477559

In [ ]:
df = df.select_dtypes(include=["object"]).join(df[final_columns])
df = df.join(df_copy["price"])

In [ ]:
categorical_columns = df.select_dtypes(include=["object"]).columns

for i in categorical_columns :
    dummies_creator = pd.get_dummies(df[i],drop_first= True, prefix = i )
    df = df.join(dummies_creator)
    df=df.drop(columns=[i])

### Min_Max_Scaling

In [ ]:

def build_min_max_scaler(df) :
  scaled_columns = pd.DataFrame()
  for i in df.columns:
      min = df[i].min()
      df[i] = df[i]-min
      max = df[i].max()
      scaled_columns[i] = pd.DataFrame( round(df[i]/max ,5) )
  return scaled_columns


df_new = build_min_max_scaler(df.drop("price",axis = 1 ))
df = df_new.join(df["price"])

# Building Model

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error
import statsmodels.api as sm

In [ ]:
X = df.drop("price",axis = 1 )
y = df["price"]

In [ ]:
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.25,random_state = 15062001 )

In [ ]:
X = sm.add_constant(X_train)
model = sm.OLS(y_train,X_train)
results = model.fit()
# Print the summary of the regression results
summary = results.summary()
print(results.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.917
Model:                            OLS   Adj. R-squared (uncentered):              0.915
Method:                 Least Squares   F-statistic:                              379.4
Date:                Thu, 03 Aug 2023   Prob (F-statistic):                    1.65e-55
Time:                        17:04:18   Log-Likelihood:                         -1015.6
No. Observations:                 106   AIC:                                      2037.
Df Residuals:                     103   BIC:                                      2045.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
horsepower  2.109e+04   1268.355     16.627      0.000    1.86e+04    2.36e+04
citympg     5676.4799   1243.984      4.563      0.000    3209.332    8143.628
symboling   2471.4202   1271.906      1.943      0.055     -51.105    4993.945
==============================================================================
Omnibus:                       11.246   Durbin-Watson:                   2.411
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               11.537
Skew:                           0.732   Prob(JB):                      0.00312
Kurtosis:                       3.686   Cond. No.                         4.39
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
y_pred = results.predict(X_test)
mse = mean_absolute_error(y_test, y_pred)
mpe = abs (np.mean((y_test - y_pred) / y_test)) * 100
print("Mean Squarred Error :" , mse)
print("Mean Percentage Error : ",mpe)

Mean Squarred Error : 1970.3300692083753
Mean Percentage Error :  1.0728893309464034

In [ ]:
tables = pd.read_html(summary.tables[1].as_html(), header=0, index_col=0)
coefficients_table = tables[0]
sorted_table = coefficients_table.sort_values(by='P>|t|', ascending=False)
pd.DataFrame(sorted_table)

                  coef   std err       t  P>|t|     [0.025     0.975]
symboling    2471.4202  1271.906   1.943  0.055    -51.105   4993.945
horsepower  21090.0000  1268.355  16.627  0.000  18600.000  23600.000
citympg      5676.4799  1243.984   4.563  0.000   3209.332   8143.628